CREATE TABLE PERSON
(
    PERSON_ID NUMBER NOT NULL,
    FODSELSNR VARCHAR2(11) NOT NULL,
    PRIMARY KEY (PERSON_ID)
);

CREATE TABLE SAK
(
    SAK_ID               NUMBER       NOT NULL,
    SAKSKODE             VARCHAR2(10) NOT NULL,
    REG_DATO             DATE,
    REG_USER             VARCHAR2(8),
    MOD_DATO             DATE,
    MOD_USER             VARCHAR2(8),
    TABELLNAVNALIAS      VARCHAR2(10) NOT NULL,
    OBJEKT_ID            NUMBER,
    AAR                  NUMBER(4)    NOT NULL,
    LOPENRSAK            NUMBER(7)    NOT NULL,
    DATO_AVSLUTTET       DATE,
    SAKSTATUSKODE        VARCHAR2(5)  NOT NULL,
    ARKIVNOKKEL          VARCHAR2(7),
    AETATENHET_ARKIV     VARCHAR2(8),
    ARKIVHENVISNING      VARCHAR2(255),
    BRUKERID_ANSVARLIG   VARCHAR2(8),
    AETATENHET_ANSVARLIG VARCHAR2(8),
    OBJEKT_KODE          VARCHAR2(10),
    STATUS_ENDRET        DATE,
    PARTISJON            NUMBER(8),
    ER_UTLAND            VARCHAR2(1)  NOT NULL,
    PRIMARY KEY (SAK_ID)
);

CREATE TABLE VEDTAK
(
    VEDTAK_ID              NUMBER       NOT NULL,
    SAK_ID                 NUMBER       NOT NULL,
    VEDTAKSTATUSKODE       VARCHAR2(5)  NOT NULL,
    VEDTAKTYPEKODE         VARCHAR2(10) NOT NULL,
    REG_DATO               DATE,
    REG_USER               VARCHAR2(8),
    MOD_DATO               DATE,
    MOD_USER               VARCHAR2(8),
    UTFALLKODE             VARCHAR2(10),
    BEGRUNNELSE            VARCHAR2(4000),
    BRUKERID_ANSVARLIG     VARCHAR2(8),
    AETATENHET_BEHANDLER   VARCHAR2(8)  NOT NULL,
    AAR                    NUMBER(4)    NOT NULL,
    LOPENRSAK              NUMBER(7)    NOT NULL,
    LOPENRVEDTAK           NUMBER(3)    NOT NULL,
    RETTIGHETKODE          VARCHAR2(10) NOT NULL,
    AKTFASEKODE            VARCHAR2(10) NOT NULL,
    BREV_ID                NUMBER,
    TOTALBELOP             NUMBER(8, 2),
    DATO_MOTTATT           DATE         NOT NULL,
    VEDTAK_ID_RELATERT     NUMBER,
    AVSNITTLISTEKODE_VALGT VARCHAR2(20),
    PERSON_ID              NUMBER,
    BRUKERID_BESLUTTER     VARCHAR2(8),
    STATUS_SENSITIV        VARCHAR2(1),
    VEDLEGG_BETPLAN        VARCHAR2(1),
    PARTISJON              NUMBER(8),
    OPPSUMMERING_SB2       VARCHAR2(4000),
    DATO_UTFORT_DEL1       DATE,
    DATO_UTFORT_DEL2       DATE,
    OVERFORT_NAVI          VARCHAR2(1),
    FRA_DATO               DATE,
    TIL_DATO               DATE,
    SF_OPPFOLGING_ID       NUMBER,
    STATUS_SOSIALDATA      VARCHAR2(1)  NOT NULL,
    KONTOR_SOSIALDATA      VARCHAR2(8),
    TEKSTVARIANTKODE       VARCHAR2(20),
    VALGT_BESLUTTER        VARCHAR2(8),
    TEKNISK_VEDTAK         VARCHAR2(1),
    DATO_INNSTILT          DATE,
    ER_UTLAND              VARCHAR2(1)  NOT NULL,
    PRIMARY KEY (VEDTAK_ID)
);

CREATE TABLE VEDTAKFAKTA
(
    VEDTAK_ID       NUMBER       NOT NULL,
    VEDTAKFAKTAKODE VARCHAR2(10) NOT NULL,
    VEDTAKVERDI     VARCHAR2(2000),
    REG_DATO        DATE,
    REG_USER        VARCHAR2(8),
    MOD_DATO        DATE,
    MOD_USER        VARCHAR2(8),
    PERSON_ID       NUMBER,
    PARTISJON       NUMBER(8),
    PRIMARY KEY (VEDTAK_ID, VEDTAKFAKTAKODE)
);
