version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    # set limit to 1 as auto-merge seems to fail if more than 1
    # trigger dependabot
    open-pull-requests-limit: 1
    assignees:
      - "@navikt/tpts"
    ignore:
      # Trenger foreløpig å ignorere noen avhengigheter, se build.gradle.kts
      - dependency-name: "io.github.threeten-jaxb:threeten-jaxb-core"
      - dependency-name: "jakarta.xml.bind:jakarta.xml.bind-api"
      - dependency-name: "jakarta.xml.soap:jakarta.xml.soap-api"
      - dependency-name: "jakarta.annotation:jakarta.annotation-api"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - "@navikt/tpts"
