kafka:
  pool: nav-dev
vaultpath: dev
ingress:
  url: https://tiltakspenger-arena.dev-fss-pub.nais.io
cluster: dev-gcp
tenant: trygdeetaten.no
azure:
  groups:
    - name: ROLE_FORTROLIG
      id: ea930b6b-9397-44d9-b9e6-f4cf527a632a
    - name: ROLE_STRENGT_FORTROLIG
      id: 5ef775f2-61f8-4283-bf3d-8d03f428aa14
    - name: ROLE_SKJERMING
      id: dbe4ad45-320b-4e9a-aaa1-73cca4ee124d
