kafka:
  pool: nav-prod
vaultpath: prod
ingress:
  url: https://tiltakspenger-arena.prod-fss-pub.nais.io
cluster: prod-gcp
vault_db_config_path: oracle/data/prod/config/arena
vault_db_creds_path: oracle/data/prod/creds/arena-arena_tilgang_ind
