apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{ name }}
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://{{ name }}.dev.intern.nav.no
  azure:
    application:
      enabled: true
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  envFrom:
    - secret: srvtpts-arena
  env:
    - name: ARENA_ORDS_URL
      value: https://arena-ords-q2.nais.preprod.local
    - name: ARENA_ORDS_CLIENT_ID # this should be a secret on the pod
      value: clientid
    - name: ARENA_ORDS_CLIENT_SECRET # this should be a secret on the pod
      value: secret
