apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-arena
  namespace: tpts
  labels:
    team: tpts
  annotations:
    texas.nais.io/enabled: "true"
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - {{ ingress.url }}
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tiltakspenger-soknad-api
          cluster: {{ cluster }}
        - application: tiltakspenger-tiltak
          namespace: tpts
          cluster: {{ cluster }}
        - application: tiltakspenger-datadeling
          namespace: tpts
          cluster: {{ cluster }}
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  strategy:
    type: RollingUpdate
  replicas:
    min: 2
    max: 2
  kafka:
    pool: {{ kafka.pool }}
  secureLogs:
    enabled: true
  webproxy: true
  envFrom:
    - secret: ords-arena
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/{{ vaultpath }}/srvtpts-arena
        mountPath: /secrets/serviceuser
      - kvPath: {{ vault_db_config_path }}
        mountPath: /secrets/dbconfig
      - kvPath: {{ vault_db_creds_path }}
        mountPath: /secrets/dbcreds
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java