apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-arena
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - {{ ingress.url }}
  resources:
    limits:
      memory: 1500Mi
    requests:
      memory: 750Mi
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
    inbound:
      rules:
        - application: tiltakspenger-tiltak
          namespace: tpts
          cluster: {{ cluster }}
        - application: tiltakspenger-datadeling
          namespace: tpts
          cluster: {{ cluster }}
        - application: tiltakspenger-saksbehandling-api
          namespace: tpts
          cluster: {{ cluster }}
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
  liveness:
    path: /isalive
    initialDelay: 15
  readiness:
    path: /isready
    initialDelay: 15
    periodSeconds: 5
    failureThreshold: 1
  prometheus:
    enabled: true
    path: /metrics
  strategy:
    type: RollingUpdate
  replicas:
    min: 2
    max: 2
  kafka:
    pool: {{ kafka.pool }}
  webproxy: true
  envFrom:
    - secret: ords-arena
  vault:
    enabled: true
    paths:
      - kvPath: {{ vault_db_config_path }}
        mountPath: /secrets/dbconfig
      - kvPath: {{ vault_db_creds_path }}
        mountPath: /secrets/dbcreds
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
