apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{ name }}
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://{{ name }}.dev.intern.nav.no
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  envFrom:
    - secret: srvtpts-arena
#  vault:
#    enabled: true
#    paths:
#      - kvPath: /serviceuser/data/dev/srvtpts-arena
#        mountPath: /secrets/serviceuser
