version: '3.8'
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.2.2
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: ERROR
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.2.2
    depends_on:
      - zookeeper
    restart: always
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_AUTO_LEADER_REBALANCE_ENABLE: false
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,BROKER://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,BROKER://kafka:9092
      TZ: Europe/Oslo
  auth:
    image: "ghcr.io/navikt/mock-oauth2-server:0.5.1"
    container_name: auth
    ports:
      - "6969:6969"
    environment:
      SERVER_PORT: 6969
      JSON_CONFIG: >
        {
            "interactiveLogin": true,
            "httpServer": "NettyWrapper",
            "tokenCallbacks": [
                {
                    "issuerId": "tokendings",
                    "tokenExpiry": 3600,
                    "requestMappings": [
                        {
                            "requestParam": "grant_type",
                            "match": "*",
                            "claims": {
                                "sub": "12345678901",
                                "pid": "12345678901",
                                "aud": ["localhost:tpts:tiltakspenger-arena"],
                                "acr": "Level4"
                            }
                        }
                    ]
                }
            ]
        }