package no.nav.tiltakspenger.arena.ytelser.domene

class Vedtak(
    // Fjern det som ikke trengs i mapping til YtelseSakDTO her

//    val vedtakId: Int,
//    val sakId: Int,
//    val vedtakstatuskode: String,
//    val vedtaktypekode: String,
//    val regDato: LocalDate?,
//    val regUser: String?,
//    val modDato: LocalDate?,
//    val modUser: String?,
//    val utfallkode: String?,
//    val begrunnelse: String?,
//    val brukeridAnsvarlig: String?,
//    val aetatenhetBehandler: String,
//    val aar: Int,
//    val lopenrsak: Int,
//    val lopenrvedtak: Int,
//    val rettighetkode: String,
//    val aktfasekode: String,
//    val brevId: Int?,
//    val totalbelop: Int?,
//    val datoMottatt: LocalDate,
//    val vedtakIdRelatert: Int?,
//    val avsnittlistekodeValgt: String?,
//    val personId: Int?,
//    val brukeridBeslutter: String?,
//    val statusSensitiv: String?,
//    val vedleggBetplan: String?,
//    val partisjon: Int?,
//    val oppsummeringSb2: String?,
//    val datoUtfortDel1: LocalDate?,
//    val datoUtfortDel2: LocalDate?,
//    val overfortNavi: String?,
//    val fraDato: LocalDate?,
//    val tilDato: LocalDate?,
//    val sfOppfolgingId: Int?,
//    val statusSosialdata: String,
//    val kontorSosialdata: String?,
//    val tekstvariantkode: String?,
//    val valgtBeslutter: String?,
//    val tekniskVedtak: String?,
//    val datoInnstilt: LocalDate?,
//    val erUtland: String,
)
