name: Auto Merge dependabot
on:
  pull_request_target:
  workflow_run:
    workflows: ["Build, push, and deploy"]
    types:
      - completed

jobs:
  dependabot:
    name: Merge
    runs-on: ubuntu-latest
    run: | 
      echo "github.actor=${{ github.actor }}"
      echo "github.event.pull_request.head.repo.full_name=${{ github.event.pull_request.head.repo.full_name }}"
      echo "github.repository=${{ github.repository }}"
      echo "github.event.workflow_run=${{ github.event.workflow_run }}"
      echo "github.event.workflow_run.conclusion=${{ github.event.workflow_run.conclusion }}"
    # Only allow dependabot from this repo, not via forks and only if build was successful
    if: github.actor == 'dependabot[bot]' && github.event.pull_request.head.repo.full_name == github.repository && github.event.workflow_run.conclusion == 'success'
    steps:
      - run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Notify Slack in case of merge failure
        if: failure()
        run: |
          curl -X POST --data-urlencode "payload={ \"attachments\": [{ \"pretext\": \"[${{ github.event.repository.name }}] Merge failed :cry:\", \"color\": \"danger\", \"fields\": [ { \"title\": \"Author\", \"value\": \"$AUTHOR\", \"short\": false }, { \"title\": \"Branch\", \"value\": \"$BRANCH\", \"short\": false }, { \"title\": \"Commit\", \"value\": \"<https://github.com/${{ github.repository }}/commit/$PR_SHA|$PR_SHA>\", \"short\": false } ] }] }" $WEBHOOK_URL
        env:
          PR_SHA: ${{ github.event.pull_request.head.sha }}
          BRANCH: ${{ github.head_ref }}
          AUTHOR: ${{ github.actor }}
          WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
