name: Tester slack-notifications
on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    env:
      PR_SHA: ${{ github.event.pull_request.head.sha }}
      WEBHOOK_URL: ${{ secrets.SLACK_VARSEL_WEBHOOK_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Notify Slack on new major version
        run: |
          curl -X POST --data-urlencode "payload={ \"attachments\": [{ \"pretext\": \"[${{ github.event.repository.name }}] Ny major dependency versjon!\", \"color\": \"info\", \"fields\": [ { \"title\": \"Commit\", \"value\": \"<https://github.com/${{ github.repository }}/commit/$PR_SHA|$PR_SHA>\", \"short\": false }, { \"title\": \"Dependency\", \"value\": \"$DEPENDENCY_NAME $VERSION_CHANGE\", \"short\": false } ] }] } ] }] }" $WEBHOOK_URL
        env:
          DEPENDENCY_NAME: Blah blah
          VERSION_CHANGE: "1.0 -> 2.0"
      - name: Notify Slack in case of merge failure
        run: |
          curl -X POST --data-urlencode "payload={ \"attachments\": [{ \"pretext\": \"[${{ github.event.repository.name }}] Merge failed :cry:\", \"color\": \"danger\", \"fields\": [ { \"title\": \"Commit\", \"value\": \"<https://github.com/${{ github.repository }}/commit/$PR_SHA|$PR_SHA>\", \"short\": false }, { \"title\": \"Dependency\", \"value\": \"$DEPENDENCY_NAME $VERSION_CHANGE\", \"short\": false } ] }] }" $WEBHOOK_URL
        env:
          DEPENDENCY_NAME: Blah blah
          VERSION_CHANGE: "1.0 -> 1.2"